### ISSUE TITLE
Translation Strings are missing!

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [Tectato/BetterCommandBlockUI#15]
In Minecraft 1.19.4 on My language I have this situation:

![image](https://github.com/Tectato/BetterCommandBlockUI/assets/51203385/706e4f45-1f7e-433f-b114-555b54cbda8d)
![image](https://github.com/Tectato/BetterCommandBlockUI/assets/51203385/6ce7f5a0-7b8b-4ba3-8c3a-7e620177822b)
![image](https://github.com/Tectato/BetterCommandBlockUI/assets/51203385/7c8922ae-d5ce-4ef7-988b-b487705d8b57)
![image](https://github.com/Tectato/BetterCommandBlockUI/assets/51203385/eaa4e3f3-d5c8-486b-87f5-eff58533fdb3)
![image](https://github.com/Tectato/BetterCommandBlockUI/assets/51203385/4ef9508c-5d0f-47fd-a432-a8608f733a8c)
![image](https://github.com/Tectato/BetterCommandBlockUI/assets/51203385/1a5e63c4-c80d-44b8-ba28-0b3334885b42)

Is it Mod-side or Vanilla-side trouble?

**Comment by Tectato** [comment]
I didn't add any translation strings yet as that would have made the toolbar layout way more complicated, and I didn't think there was much demand for it since commands are written in english anyways and the command block interface really isn't something that non-technical players will see very often. I'll have to overhaul parts of the code anyways so I'll add translation strings then, but translations for a given language will have to be submitted by people who speak it.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> I didn't add any translation strings yet as that would have made the toolbar layout way more complicated, and I didn't think there was much demand for it since commands are written in english anyways and the command block interface really isn't something that non-technical players will see very often. I'll have to overhaul parts of the code anyways so I'll add translation strings then, but translations for a given language will have to be submitted by people who speak it.

Thank You for the answer!

**Comment by Tectato** [comment]
Translation strings have been added. The mod currently supports english and german, if you want to submit your own translation for another language you can open a pull request
